# TODO: remove "as build" clause
FROM ubuntu:17.10 AS build
RUN apt-get update && apt-get install -y apt-utils && \
    apt-get install -y python3 python3-pip python3-venv && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app/
COPY requirements.txt .coveragerc /app/
RUN pip3 --quiet --disable-pip-version-check --no-cache-dir install -r requirements.txt

ENV PYTHONPATH=/app/src
COPY .coveragerc /app/
COPY src /app/src/
COPY tests /app/tests/
RUN py.test --cov-config=./.coveragerc --cov-report=term-missing --cov-branch --cov=./src/ tests/
