FROM infolinks/deployster-k8s-configmap:local
COPY src/k8s_secret.py /deployster/lib/
RUN chmod +x /deployster/lib/k8s_secret.py && chmod -x /deployster/lib/k8s_configmap.py
ENTRYPOINT ["/deployster/lib/k8s_secret.py"]
CMD ["init"]
