FROM infolinks/deployster-dresource:local
RUN gcloud components install kubectl
COPY src/k8s*.py /deployster/lib/
RUN chmod +x /deployster/lib/k8s_main.py
ENTRYPOINT ["/deployster/lib/k8s_main.py"]
CMD ["init"]
