FROM infolinks/deployster-gcp:local
RUN curl -sSL -o "/usr/local/bin/cloud_sql_proxy" "https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64" && \
    chmod +x /usr/local/bin/cloud_sql_proxy && \
    yum install -y mariadb && yum clean all
COPY src/gcp_cloud_sql.py /deployster/lib/
RUN chmod +x /deployster/lib/gcp_cloud_sql.py
ENTRYPOINT ["/deployster/lib/gcp_cloud_sql.py"]
CMD ["init"]
