FROM infolinks/deployster-k8s:local
COPY src/k8s_rbac_role_binding.py /deployster/lib/
RUN chmod +x /deployster/lib/k8s_rbac_role_binding.py
ENTRYPOINT ["/deployster/lib/k8s_rbac_role_binding.py"]
CMD ["init"]
