FROM infolinks/deployster-gcp:local
COPY src/dresources_util.py src/dresources.py src/external_services.py /deployster/lib/
COPY src/gcp_project.py /deployster/lib/
RUN chmod +x /deployster/lib/gcp_project.py
ENTRYPOINT ["/deployster/lib/gcp_project.py"]
CMD ["init"]
