FROM infolinks/deployster-gcp:local
COPY src/gcp_gke_cluster.py src/gcp_project.py /deployster/lib/
RUN chmod +x /deployster/lib/gcp_gke_cluster.py
ENTRYPOINT ["/deployster/lib/gcp_gke_cluster.py"]
CMD ["init"]
