FROM infolinks/deployster-k8s:local
COPY src/k8s_namespace.py src/k8s_ingress.py /deployster/lib/
RUN chmod +x /deployster/lib/k8s_ingress.py
ENTRYPOINT ["/deployster/lib/k8s_ingress.py"]
CMD ["init"]
